server:
  port: 6061

spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://192.168.60.12:3306/etimesheet?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: everyone
    password: a12345678!
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
mybatis:
  mapper-locations:
    - classpath*:mapper/*.xml
  type-aliases-package: com.worktime.entity
path-config:
  path:
    include:
     -/login.html
     -/user/login
     -/assets/**
     -/css/**
     -/images/**
     -/js/**
     -/vendors/**
     -/webfonts/**